### ISSUE TITLE
Report dates and time ranges are unclear

### ISSUE THREAD

**Issue by natanlao** [ucsc-cgp/cloud-billing-report#16]
There is a discrepancy in the presentation of reporting periods for both reports. For the AWS report:

* AWS deposits billing data for the current day two to three times per day at different times in the day. (For example, the latest billing CSV with data for today, August 18, became available Aug 18 at 12:55:27 PT.)
* The AWS reporting script runs daily at 6am. It will use the latest billing CSV, whether it was generated on the day or the day before. For example, today's generated generated report had the subject `Amazon Web Services Report for August 18, 2020` and used billing data generated at 05:02 PT 18 Aug.
* The generated report will display the difference between the most recent billing CSV (e.g., with data from no later than 6am 18 Aug) and the most recent billing CSV at the time that the script was run the day before (e.g., with data from no later than 6am 17 Aug) under the "yesterday" column.

For the GCP report:

* GCP deposits billing data for the previous day around 5am PT. (For example, the billing CSV `billing-report--2020-08-17.csv` landed in Google Cloud Storage at `2020-08-18T11:59:30Z`, or 04:59 PT.)
* The GCP reporting script runs daily at 5pm PT. The generated report will have the subject `Google Cloud Platform Report for August 18, 2020`.
* The generated report will display the difference between the most recent billing CSV (e.g. 17 Aug) and the second-most-recent billing CSV (e.g. 16 Aug) under the "yesterday" column.

This discrepancy can be confusing.

**Comment by melainalegaspi** [comment]
@hannes-ucsc come up with a solution

**Comment by hannes-ucsc** [comment]
At a high level this is the desired behaviour. Given a particular cloud provider (AWS or GCP),

1. Exactly one report MUST be generated for every day. That report must cover all charges incurred by that provider during that day, between 00:00:00 PT and 24:59:59 PT (this is usually a 24h period, but in the spring (fall) there will be one report covering 23h (25h). This interval is henceforth referred to as the *reporting interval* of the report.
2. The email containing a report SHOULD be sent within 12 hours after the end of the reporting interval.
3. Tooling MUST exist to retroactively send report emails for the most recent 100 reporting intervals.
4. The report  MUST contain two cost columns.
5. The second cost column of a report MUST contain the costs incurred for that line item (the row) during the reporting interval of the report.
6. The first cost column of a report MUST contain the sum of all costs incurred for that line item (the row) during all reporting intervals that fall into the same month as the reporting interval of the report. A reporting interval falls into exactly one month so there is no ambiguity there. If a particular report failed to report certain costs due to bugs or outages, the next successful report should account for that cost in the first column.
7. The header of the first column is the month and year portion of the date of the reporting interval in the form `MM/YYYY`.
8. The header of the second column is entire date of the reporting interval `MM/DD/YYYY`.
9. That same date is used for the title of the report and the subject of the report email.

Based on this we can negotiate what's technically possible.

**Comment by natanlao** [comment]
Here's my proposal:

> 1 . Exactly one report MUST be generated for every day. That report must cover all charges incurred by that provider during that day, between 00:00:00 PT and 24:59:59 PT (this is usually a 24h period, but in the spring (fall) there will be one report covering 23h (25h). This interval is henceforth referred to as the reporting interval of the report.
> 2. The email containing a report SHOULD be sent within 12 hours after the end of the reporting interval.
> 3. Tooling MUST exist to retroactively send report emails for the most recent 100 reporting intervals.
> 6. The first cost column of a report MUST contain the sum of all costs incurred for that line item (the row) during all reporting intervals that fall into the same month as the reporting interval of the report. A reporting interval falls into exactly one month so there is no ambiguity there. If a particular report failed to cover certain costs due to bugs or outages, a subsequent successful report for the same month SHOULD account for that cost in the first column. Tooling must exist to resend corrected reports retroactively.

The script has functionality to generate previous reports, but it's error-prone and tedious. I can make this easier by removing reliance on a database for storing historical data. This functionality is an artifact of the old billing system; it was necessary to store historical data because we would lose "raw" billing data regularly. This is no longer the case, and removing this functionality would...
* Improve report accuracy
* Enable streamlined generation of accurate reports for any reporting interval for which AWS-provided billing data exists
* Remove a subtle (and incorrect) brittle coupling in cost calculation

This work would make it trivial for an administrator (i.e., Erich) to manually generate reports for past dates. If you find it appropriate, I can add a tool that automatically generates past reports that could not be sent.

> 4. The report MUST contain two cost columns.
> 5. The second cost column of a report MUST contain the costs incurred for that line item (the row) during the reporting interval of the report.

The report already does this, but the suggestions above will make this much more reliable.

> 7. The header of the first column is the month and year portion of the date of the reporting interval in the form MM/YYYY.
> 8. The header of the second column is entire date of the reporting interval MM/DD/YYYY.
> 9. That same date is used for the title of the report and the subject of the report email.

This can be implemented trivially and independently of the above suggestions. It's also much clearer.

**Comment by natanlao** [comment]
After discussing at standup, the new approach is to synchronize billing CSVs with a local database periodically, then to generate reports by querying the database. This is because in the future, we want to be able to run larger queries on spending.

This can be split up into a set of smaller parts:
- Modify reports to calculate diffs, totals without referencing database
- Modify script to synchronize CSVs with a local database
- Modify reports to calculate diffs, totals from database only

Maybe rewrite this in Python down the road.

**Comment by natanlao** [comment]
Split off the last half of those tasks to #26
