### ISSUE TITLE
Add RDS and kinesis services

### ISSUE THREAD

**Issue by david4096** [ucsc-cgp/cloud-billing-report#20]
Dockstore uses RDS and kinesis and would like insight into whether we are spending on those and how much.

**Comment by melainalegaspi** [comment]
Spike to verify RDS and kinesis are actually missing from the report.

**Comment by natanlao** [comment]
I've manually verified with the billing data:
* RDS is being displayed appropriately in the report in both oicr-dockstore and dockstore-dev
* Kinesis activity is being logged to dockstore-dev, but is not being displayed in the report because the total cost of that activity is $0.00

Services generally don't need to be added manually; as soon as usage of a service incurs cost, it will appear on the next billing report. It might be appropriate to display services with registered activity but no accrued cost; I'll run this by Hannes.

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "based on Natan's assessment, this works as intended."
