### ISSUE TITLE
Problem in oicr-dockstore report

### ISSUE THREAD

**Issue by david4096** [ucsc-cgp/cloud-billing-report#21]
We have an item in yesterdays cost that doesn't seem correct. The month column is empty for this entry as well.

Related https://github.com/ucsc-cgp/cloud-billing-report/issues/20

**Comment by natanlao** [comment]
For context, I spoke to @david4096 and believe he is referring to the "Unknown Services" row. Two considerations:

* The "This month" value for "Unknown Services" is always N/A; it tracks the sum of all services that are not currently tracked in the database. This is a known limitation, and may be resolved as a result of #16.
* The "Yesterday" value for "Unknown Services" should be the total growth of all untracked services since the last report. (To be clear, we know the per-service cost breakdown for "today's" report, but we don't have that breakdown for all days preceding.) This value appears inconsistent with yesterday's report.

**Comment by melainalegaspi** [comment]
Spike to verify the inconsistency.

**Comment by natanlao** [comment]
This is a bug. The *Unknown Services* line item is calculated incorrectly, leading the "Yesterday" value to be displayed as the total accrual for the billing period.

This will be fully resolved by #16, but I already have a fix for it that I can push to Erich today.

**Comment by natanlao** [comment]
@david4096 This is fixed in [aws/2020-09-22](https://github.com/ucsc-cgp/cloud-billing-report/releases/tag/aws%2F2020-09-22) and I've forwarded it to Erich. You should see this reflected in reports by the end of the week.

**Comment by natanlao** [comment]
From @hannes-ucsc: since this ticket cannot be demoed anymore (as #16 has removed the Unknown Services line-item entirely), demonstrate work in #16 that removes the Unknown Services line item.
